export const ROBOT_SPRITE_ANIM_LIST = {
  dead: [
    "png/Dead (1).png",
    "png/Dead (2).png",
    "png/Dead (3).png",
    "png/Dead (4).png",
    "png/Dead (5).png",
    "png/Dead (6).png",
    "png/Dead (7).png",
    "png/Dead (8).png",
    "png/Dead (9).png",
    "png/Dead (10).png",
  ],
  shoot: [
    "png/Shoot (1).png",
    "png/Shoot (2).png",
    "png/Shoot (3).png",
    "png/Shoot (4).png",
  ],
  runShoot: [
    "png/RunShoot (1).png",
    "png/RunShoot (2).png",
    "png/RunShoot (3).png",
    "png/RunShoot (4).png",
    "png/RunShoot (5).png",
    "png/RunShoot (6).png",
    "png/RunShoot (7).png",
    "png/RunShoot (8).png",
    "png/RunShoot (9).png",
  ],
  run: [
    "png/Run (1).png",
    "png/Run (2).png",
    "png/Run (3).png",
    "png/Run (4).png",
    "png/Run (5).png",
    "png/Run (6).png",
    "png/Run (7).png",
    "png/Run (8).png",
  ],
  runReverse: [
    "png/Run (8).png",
    "png/Run (7).png",
    "png/Run (6).png",
    "png/Run (5).png",
    "png/Run (4).png",
    "png/Run (3).png",
    "png/Run (2).png",
    "png/Run (1).png",
  ],
  mele: [
    "png/Melee (1).png",
    "png/Melee (2).png",
    "png/Melee (3).png",
    "png/Melee (4).png",
    "png/Melee (5).png",
    "png/Melee (6).png",
    "png/Melee (7).png",
    "png/Melee (8).png",
  ],
  jumpShoot: [
    "png/JumpShoot (1).png",
    "png/JumpShoot (2).png",
    "png/JumpShoot (3).png",
    "png/JumpShoot (4).png",
    "png/JumpShoot (5).png",
  ],
  jumpMele: [
    "png/JumpMelee (1).png",
    "png/JumpMelee (2).png",
    "png/JumpMelee (3).png",
    "png/JumpMelee (4).png",
    "png/JumpMelee (5).png",
    "png/JumpMelee (6).png",
    "png/JumpMelee (7).png",
    "png/JumpMelee (8).png",
  ],
  jump: [
    "png/Jump (1).png",
    "png/Jump (2).png",
    "png/Jump (3).png",
    "png/Jump (4).png",
    "png/Jump (5).png",
    "png/Jump (6).png",
    "png/Jump (7).png",
    "png/Jump (8).png",
    "png/Jump (9).png",
    "png/Jump (10).png",
  ],
  idle: [
    "png/Idle (1).png",
    "png/Idle (2).png",
    "png/Idle (3).png",
    "png/Idle (4).png",
    "png/Idle (5).png",
    "png/Idle (6).png",
    "png/Idle (7).png",
    "png/Idle (8).png",
    "png/Idle (9).png",
    "png/Idle (10).png",
  ],
};

export const DINO_SPRITE_ANIM_LIST = {
  dead: [
    "Dead (1).png",
    "Dead (2).png",
    "Dead (3).png",
    "Dead (4).png",
    "Dead (5).png",
    "Dead (6).png",
    "Dead (7).png",
    "Dead (8).png",
  ],
  idle: [
    "Idle (1).png",
    "Idle (2).png",
    "Idle (3).png",
    "Idle (4).png",
    "Idle (5).png",
    "Idle (6).png",
    "Idle (7).png",
    "Idle (8).png",
    "Idle (9).png",
    "Idle (10).png",
  ],
};

export const GAME_ASSETS = {
  borderTile: ["Tiles/BGTile (1).png"],
  borderTileVertical: ["Tiles/BGTile (2).png"],
  bgTile: ["Tiles/BGTile (6).png"],
  box: ["Objects/Box.png"],
};
