export const ROBOT_SPRITE_ANIM_LIST = {
  dead: [
    "png/Dead (1).png",
    "png/Dead (2).png",
    "png/Dead (3).png",
    "png/Dead (4).png",
    "png/Dead (5).png",
    "png/Dead (6).png",
    "png/Dead (7).png",
    "png/Dead (8).png",
    "png/Dead (9).png",
    "png/Dead (10).png",
  ],
  shoot: [
    "png/Shoot (1).png",
    "png/Shoot (2).png",
    "png/Shoot (3).png",
    "png/Shoot (4).png",
  ],
  runShoot: [
    "png/RunShoot (1).png",
    "png/RunShoot (2).png",
    "png/RunShoot (3).png",
    "png/RunShoot (4).png",
    "png/RunShoot (5).png",
    "png/RunShoot (6).png",
    "png/RunShoot (7).png",
    "png/RunShoot (8).png",
    "png/RunShoot (9).png",
  ],
  run: [
    "png/Run (1).png",
    "png/Run (2).png",
    "png/Run (3).png",
    "png/Run (4).png",
    "png/Run (5).png",
    "png/Run (6).png",
    "png/Run (7).png",
    "png/Run (8).png",
  ],
  runReverse: [
    "png/Run (8).png",
    "png/Run (7).png",
    "png/Run (6).png",
    "png/Run (5).png",
    "png/Run (4).png",
    "png/Run (3).png",
    "png/Run (2).png",
    "png/Run (1).png",
  ],
  mele: [
    "png/Melee (1).png",
    "png/Melee (2).png",
    "png/Melee (3).png",
    "png/Melee (4).png",
    "png/Melee (5).png",
    "png/Melee (6).png",
    "png/Melee (7).png",
    "png/Melee (8).png",
  ],
  jumpShoot: [
    "png/JumpShoot (1).png",
    "png/JumpShoot (2).png",
    "png/JumpShoot (3).png",
    "png/JumpShoot (4).png",
    "png/JumpShoot (5).png",
  ],
  jumpMele: [
    "png/JumpMelee (1).png",
    "png/JumpMelee (2).png",
    "png/JumpMelee (3).png",
    "png/JumpMelee (4).png",
    "png/JumpMelee (5).png",
    "png/JumpMelee (6).png",
    "png/JumpMelee (7).png",
    "png/JumpMelee (8).png",
  ],
  jump: [
    "png/Jump (1).png",
    "png/Jump (2).png",
    "png/Jump (3).png",
    "png/Jump (4).png",
    "png/Jump (5).png",
    "png/Jump (6).png",
    "png/Jump (7).png",
    "png/Jump (8).png",
    "png/Jump (9).png",
    "png/Jump (10).png",
  ],
  idle: [
    "png/Idle (1).png",
    "png/Idle (2).png",
    "png/Idle (3).png",
    "png/Idle (4).png",
    "png/Idle (5).png",
    "png/Idle (6).png",
    "png/Idle (7).png",
    "png/Idle (8).png",
    "png/Idle (9).png",
    "png/Idle (10).png",
  ],
};

export const BOMB_SPRITES = {
  idle: ["1-Bomb Off/1"],
  bombOn: [
    "2-Bomb On/1",
    "2-Bomb On/2",
    "2-Bomb On/3",
    "2-Bomb On/4",
    "2-Bomb On/5",
    "2-Bomb On/6",
    "2-Bomb On/7",
    "2-Bomb On/8",
    "2-Bomb On/9",
    "2-Bomb On/10",
  ],
  explosion: [
    "3-Explotion/1",
    "3-Explotion/2",
    "3-Explotion/3",
    "3-Explotion/4",
    "3-Explotion/5",
    "3-Explotion/6",
    "3-Explotion/7",
    "3-Explotion/8",
    "3-Explotion/9",
  ],
  sequence: [
    "1-Bomb Off/1",
    "2-Bomb On/1",
    "2-Bomb On/2",
    "2-Bomb On/3",
    "2-Bomb On/4",
    "2-Bomb On/5",
    "2-Bomb On/6",
    "2-Bomb On/7",
    "2-Bomb On/8",
    "2-Bomb On/9",
    "2-Bomb On/10",
    "2-Bomb On/1",
    "2-Bomb On/2",
    "2-Bomb On/3",
    "2-Bomb On/4",
    "2-Bomb On/5",
    "2-Bomb On/6",
    "2-Bomb On/7",
    "2-Bomb On/8",
    "2-Bomb On/9",
    "2-Bomb On/10",
    "2-Bomb On/1",
    "2-Bomb On/2",
    "2-Bomb On/3",
    "2-Bomb On/4",
    "2-Bomb On/5",
    "2-Bomb On/6",
    "2-Bomb On/7",
    "2-Bomb On/8",
    "2-Bomb On/9",
    "2-Bomb On/10",
    "3-Explotion/1",
    "3-Explotion/2",
    "3-Explotion/3",
    "3-Explotion/4",
    "3-Explotion/5",
    "3-Explotion/6",
    "3-Explotion/7",
    "3-Explotion/8",
    "3-Explotion/9",
  ],
};

export const DINO_SPRITE_ANIM_LIST = {
  dead: [
    "Dead (1).png",
    "Dead (2).png",
    "Dead (3).png",
    "Dead (4).png",
    "Dead (5).png",
    "Dead (6).png",
    "Dead (7).png",
    "Dead (8).png",
  ],
  idle: [
    "Idle (1).png",
    "Idle (2).png",
    "Idle (3).png",
    "Idle (4).png",
    "Idle (5).png",
    "Idle (6).png",
    "Idle (7).png",
    "Idle (8).png",
    "Idle (9).png",
    "Idle (10).png",
  ],
};

export const GAME_ASSETS = {
  borderTile: ["Tiles/BGTile (1).png"],
  borderTileVertical: ["Tiles/BGTile (2).png"],
  bgTile: ["Tiles/BGTile (6).png"],
  bgTileTwo: ["Tiles/BGTile (5).png"],
  box: ["Objects/Box.png"],
  bottomBorder: ["Tiles/Tile (2).png"],
  explosionBarrel: ["Objects/Barrel (1).png"],
  acidBarrel: ["Objects/Barrel (2).png"],
  doorLocked: ["Objects/DoorLocked.png"],
  doorUnlocked: ["Objects/DoorUnlocked.png"],
  doorOpen: ["Objects/DoorOpen.png"],
  controlPanelOn: ["Objects/Switch (1).png"],
  controlPanelOff: ["Objects/Switch (2).png"],
};

export const FLAME_SPRITES = {
  bigFlame: [
    "2/1_0.png",
    "2/1_1.png",
    "2/1_2.png",
    "2/1_3.png",
    "2/1_4.png",
    "2/1_5.png",
    "2/1_6.png",
    "2/1_7.png",
    "2/1_8.png",
    "2/1_9.png",
    "2/1_10.png",
    "2/1_11.png",
    "2/1_12.png",
    "2/1_13.png",
    "2/1_14.png",
    "2/1_15.png",
    "2/1_16.png",
    "2/1_17.png",
    "2/1_18.png",
    "2/1_19.png",
    "2/1_20.png",
    "2/1_21.png",
    "2/1_22.png",
    "2/1_23.png",
    "2/1_24.png",
    "2/1_25.png",
    "2/1_26.png",
    "2/1_27.png",
    "2/1_28.png",
    "2/1_29.png",
    "2/1_30.png",
    "2/1_31.png",
    "2/1_32.png",
    "2/1_33.png",
    "2/1_34.png",
    "2/1_35.png",
    "2/1_36.png",
    "2/1_37.png",
    "2/1_38.png",
    "2/1_39.png",
    "2/1_40.png",
    "2/1_41.png",
    "2/1_42.png",
    "2/1_43.png",
    "2/1_44.png",
    "2/1_45.png",
    "2/1_46.png",
    "2/1_47.png",
    "2/1_48.png",
    "2/1_49.png",
    "2/1_50.png",
    "2/1_51.png",
    "2/1_52.png",
    "2/1_53.png",
    "2/1_54.png",
    "2/1_55.png",
    "2/1_56.png",
    "2/1_57.png",
    "2/1_58.png",
    "2/1_59.png",
    "2/1_60.png",
  ],
};
